strictness: veryhigh
max-line-length: 90
ignore-paths:
  - setup.py
  - examples/
  - .github/
python-targets:
  - 3
pep8:
  disable:
    - N803
    - N806
pylint:
  options:
    good-names: _,a,b,e,k,v,X,x,y,Xnum,Xcat,Xenc
    # Regular expression matching correct variable names
    variable-rgx: "[a-z_][a-z0-9_]{1,30}$"
    # Maximum number of arguments for function / method
    max-args: 8
    # Maximum number of locals for function / method body
    max-locals: 20
    # Minimum number of public methods for a class (see R0903).
    min-public-methods: 1
