branches:
  only:
    - master
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
# Install dependencies
install:
  - pip install --upgrade pip
  - travis_wait pip install scipy
  - travis_wait python setup.py install
  - pip install coveralls

# Run tests
script:
  - nosetests --with-coverage

# Calculate coverage
after_success:
  coveralls
